### ISSUE TITLE
Error while open the backend CMS page

### ISSUE THREAD

**Issue by chrisvidal** [lovata/oc-shopaholic-demo-theme#4]
##### Actual behavior
(Describe actual behavior here)
````
Undefined class constant 'NAME'
/Users/chrisvidal/Sites/oc-voilaah/plugins/lovata/goodnews/components/ArticleList.php line 68
````

##### Reproduce steps
Navigate to backend CMS page

##### October build
437

**Comment by kharanenka** [comment]
GoodNews plugin is not ready for use. It is not published in OctoberCMS marketplace and it still needs to be developed

**Comment by chrisvidal** [comment]
got it, thanks
