### ISSUE TITLE
Lovata.BaseCode ?

### ISSUE THREAD

**Issue by chrisvidal** [lovata/oc-shopaholic-demo-theme#5]
In the README you are referring to Lovata.BaseCode plugin, where can I find this please?

**Comment by kharanenka** [comment]
Lovata.BaseCode plugin is in one repository with demo theme.
https://github.com/lovata/oc-shopaholic-demo-theme/tree/master/plugins/lovata/basecode

**Comment by chrisvidal** [comment]
oh got it, thanks
